---
code_quality:
  script:
    - flake8
  stage: code_quality
default:
  before_script:
    - "apt -y update"
    - "apt -y install apt-utils"
    - "apt -y install net-tools python3.8 python3-pip mysql-client libmysqlclient-dev"
    - "apt -y upgrade"
    - "pip3 install -r requirements.txt"
  cache:
    paths:
      - ~/.cache/pip/
  image: "ubuntu:20.04"
  services:
    - "mysql:8.0"
deploy_develop:
  before_script:
    - "gem install dpl"
    - "wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh"
  image: "ruby:2.4"
  script:
    - "heroku run --app $HEROKU_APPNAME python pip install -r requirements.txt"
    - "heroku run --app $HEROKU_APPNAME python manage.py migrate"
    - "dpl --provider=heroku --app=$HEROKU_NAME_DEV  --api-key=$HEROKU_API_KEY"
  stage: deploy_develop
  tags:
    - dalfcs_gitlab_docker_ci
migrations:
  script:
    - "python3 manage.py makemigrations"
    - "python3 manage.py makemigrations farmfoodapp"
    - "python3 manage.py migrate"
    - "python3 manage.py check"
  stage: build
stages: "-deploy_develop"
test_case:
  script:
    - "python3 manage.py test farmfoodapp"
  stage: test
variables:
  MYSQL_DATABASE: $MYSQL_DATABASE
  MYSQL_HOST: $MYSQL_HOST
  MYSQL_PASSWORD: $MYSQL_PASSWORD
  MYSQL_USER: $MYSQL_USER
